### PR TITLE
added docker answer

### PR DESCRIPTION
**Pull request by maglovskiNenad**

### CODE REVIEW

**Review by moabukar — APPROVED** [review]
Thanks for the contribution! LGTM

Feel free to answer more of the questions. I have left out some of the answers on purpose so the community can add their answers 🙌🏼

**Comment by maglovskiNenad** [comment]
Thank you very much for allowing me to participate, I will try to answer as many questions as possible.

**Comment by moabukar** [comment]
@maglovskiNenad Feel free to merge.

**Comment by maglovskiNenad** [comment]
added one more answer(Linux answer)

**Pull request merged**
